name: Action Dispatch

on: [repository_dispatch]

jobs:
  manual_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: respository dispatch testing
        env:
          DISPATCH_PAYLOAD: ${{ toJson(github.event) }} 
        run: |
             echo "$DISPATCH_PAYLOAD"
